// <auto-generated />
// Licensed under the MIT license.
// Copyright (c) The AppCore .NET project.

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace AppCoreNet.Diagnostics;

/// <summary>
/// Provides helper methods to ensure program contracts such as preconditions, postconditions, and invariants.
/// </summary>
#if !APPCORENET_SHARED_SOURCES_TESTS
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#endif
internal static partial class Ensure
{
}