version: 1.0.0-alpha.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build_script:
- pwsh: ./build.ps1