version: 'ci-build-{build}'

pull_requests:
  do_not_increment_build_number: true

image:
- Visual Studio 2017
- Ubuntu

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj, **\*.props, **\*.targets'
  - '/home/appveyor/.nuget/packages -> **/*.csproj, **/*.props, **/*.targets'

nuget:
  disable_publish_on_pr: true

install:
- ps: |
    Write-Host "Installing .NET Core SDK..." -ForegroundColor Cyan
    Write-Host "Downloading..."
    $exePath = "$env:TEMP\dotnet-sdk.exe"
    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/8148cce0-196d-4634-86df-f3d4550b1a75/89ed68d0ecf6b1c62cc7b0d129fdf600/dotnet-sdk-2.2.105-win-x64.exe', $exePath)
    Write-Host "Installing..."
    cmd /c start /wait "$exePath" /quiet /norestart
    del $exePath
    Write-Host "Installed" -ForegroundColor Green
  
configuration: Debug
build_script:
- pwsh: ./build.ps1 -Configuration $env:CONFIGURATION -BuildNumber $env:APPVEYOR_BUILD_NUMBER -CI
test_script:
- pwsh: ./test.ps1 -Configuration $env:CONFIGURATION

branches:
  except:
  - /^release\/.*$/

artifacts:
  - path: '**/*.*nupkg'
    name: NuGet Packages

deploy:
  provider: NuGet
  name: MyGet
  on:
    branch: dev
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  server: https://www.myget.org/F/appcorenet/api/v2/package
  api_key:
    secure: eB0zjsEqa4oBKHhgwqhd62CdOG5YIKyTHEApHF9xwxuxjplKdIKBYEn2R2/6ITOb
  artifact: /.*\.nupkg/
