name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  configuration: Debug

trigger:
- dev
- master

pr:
  autoCancel: true

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - pwsh: ./build.ps1 -Configuration $(configuration) -CI
    displayName: Build
  - pwsh: ./test.ps1 -Configuration $(configuration)
    displayName: Run Tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - pwsh: ./build.ps1 -Configuration $(configuration) -CI
    displayName: Build
  - pwsh: ./test.ps1 -Configuration $(configuration)
    displayName: Run Tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      failTaskOnFailedTests: true
