name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  configuration: Debug

trigger:
- dev

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: build/shared/azure-pipelines/build-steps.yml
    parameters:
      configuration: $(configuration)
  - template: build/shared/azure-pipelines/publish-steps.yml
    parameters:
      configuration: $(configuration)  

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: export DOTNET_ROOT="$(dirname "$(readlink "$(command -v dotnet)")")"
  - template: build/shared/azure-pipelines/build-steps.yml
    parameters:
      configuration: $(configuration)
      
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: build/shared/azure-pipelines/build-steps.yml
    parameters:
      configuration: $(configuration)
