name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  configuration: Debug

trigger:
- dev
- master

pr:
  autoCancel: true

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: build/azure-pipeline-steps.yml
    parameters:
      configuration: $(configuration)

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: build/azure-pipeline-steps.yml
    parameters:
      configuration: $(configuration)
