name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  configuration: Debug

trigger:
- dev

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: build/shared/azure-pipelines/build-steps.yml
    parameters:
      configuration: $(configuration)
  - template: build/shared/azure-pipelines/publish-steps.yml
    parameters:
      configuration: $(configuration)  

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: build/shared/azure-pipelines/build-steps.yml
    parameters:
      configuration: $(configuration)
