// <auto-generated />

#if !NETCOREAPP3_0_OR_GREATER && !NETSTANDARD2_1_OR_GREATER && APPCORENET_ATTRIBUTES_ENABLED && APPCORENET_NULLABLE_ATTRIBUTES_ENABLED

// ReSharper disable once CheckNamespace
namespace System.Diagnostics.CodeAnalysis;

/// <summary>
/// Specifies that an output is not <see langword="null"/> even if the
/// corresponding type allows it.
/// </summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.ReturnValue)]
internal sealed class NotNullAttribute : Attribute
{
}

#endif